version: 2

sources:
  - name: source # This is because in databricks our schema name is source
    database: dbt_psangang_dev  # This is databricks catalog name
    schema: source  # By default, schema should be same as name. Since, our schema is source, we are using same name here.
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
      - name: items
      

      

